// ============================================================================
// tb_svm_classifier.sv  —  ECE410_project_LUT
// ============================================================================
// Full-pipeline classification testbench for svm_compute_core.
//
// Tests 5 heartbeats (one per class: Normal, PVC, AFib, VT, SVT) using
// parameters and data generated by gen_tb_data.py.
//
// Key difference from ECE410_project_updated version:
//   gamma = 0.25  →  Q6.10 = 256 = 16'h0100
//   Range-reduction LUT kernel pre-computed by gen_tb_data.py
//   Multi-scale 256-dim features (128 beat + 64 mean + 64 RR)
//
// Per-heartbeat sequence:
//   1.  Assert async reset, release synchronously.
//   2.  Program gamma = 0.25 (0x0100) via param_write_en interface.
//   3.  Set num_sv_per_class for all 5 classes.
//   4.  Pulse start, then stream 256 feature words through QSPI interface.
//   5.  Model the external SV RAM: respond to sv_ram_addr/sv_ram_ren.
//   6.  Accept kernel outputs via kernel_valid/kernel_ready (always ready).
//   7.  Apply OvO decision function using real dual_coef/intercept from
//       tb_svm_params.svh.
//   8.  Compare predicted class to expected; log all details.
//
// Grading
//   PASS  correct_count >= PASS_THRESH (4/5 = 80%) AND error never asserted
//   FAIL  otherwise
//
// Output files
//   svm_classifier.log       per-heartbeat detail + final grade
//   svm_waveform_hb0.vcd     waveform capture for heartbeat 0 (depth 2)
//
// Simulation command (iverilog):
//   iverilog -g2012 -o tb_svm tb_svm_classifier.sv svm_compute_core.sv
//   vvp tb_svm
//
// ── Pre-netlist companion testbenches ────────────────────────────────────────
// The following targeted testbenches must all pass before proceeding to
// synthesis.  Run each independently (no shared state with this file).
//
//  tb_error_codes.sv     ERR_SV_ZERO/OVERFLOW/GAMMA_SAT/FIFO_OVERFLOW,
//                        sticky-latch, reset-clears (two DUT instances)
//  tb_backpressure.sv    kernel_ready=0 stall; documents 1-cycle valid window
//  tb_multi_heartbeat.sv num_samples=3 loop-back: FSM returns to LOAD_FIFO
//  tb_dist_boundary.sv   accumulator saturation: feature=0x7FFF, sv=0x8000
//                        → dist_out=0xFFFFF → kernel_out=0
//  tb_dist_zero.sv       feature=sv=0x0400 → dist=0 → kernel_out=1024
//  tb_consecutive.sv     two full batches back-to-back without rst_n
//  tb_param_write.sv     gamma write mid-COMPUTE_DIST → ERR_GAMMA_SAT;
//                        documents RTL bug (gamma not latched at start)
//  tb_gamma_zero.sv      gamma=0 → all kernels=1024 silent failure;
//                        recommends ERR_GAMMA_ZERO (code 0x6)
//  tb_min_sv.sv          sv_counts=[1,1,1,1,1] → 5 kernels, all=1024
//
// Known pre-netlist issues surfaced by these testbenches:
//   1. kernel_valid held for only 1 cycle (backpressure requires same-cycle
//      kernel_ready assertion — see tb_backpressure.sv sub-test C).
//   2. gamma_int not latched at start; a mid-compute write corrupts the
//      kernel result (see tb_param_write.sv).
//   3. gamma=0 produces no error flag (silent constant-1 kernel).
// ============================================================================

`timescale 1ns/1ps

module tb_svm_classifier;

// ─────────────────────────────────────────────────────────────────────────────
// Parameters from generated include (localparams + real arrays)
// ─────────────────────────────────────────────────────────────────────────────
`include "tb_svm_params.svh"
// Provides:
//   localparam int N_SV_TOTAL   (495)
//   localparam int NUM_SV_INST  (500)
//   localparam int N_TEST       (5)
//   localparam int N_PAIRS      (10)
//   integer SV_COUNTS[5]
//   integer SV_START[5]
//   real DUAL_COEF_0..3[N_SV_TOTAL]
//   real INTERCEPT[10]
//   string CLASS_NAME[5]

// ─────────────────────────────────────────────────────────────────────────────
// Module-level constants
// ─────────────────────────────────────────────────────────────────────────────
localparam int DATA_WIDTH  = 16;
localparam int FEATURE_DIM = 256;
localparam int PASS_THRESH = 4;         // >= 4/5 = 80% to PASS
localparam int KERNEL_TOL  = 2;         // ±2 Q6.10 LSBs tolerance
localparam real SCALE_R    = 1024.0;
localparam int  RAM_SIZE   = NUM_SV_INST * FEATURE_DIM;

// ─────────────────────────────────────────────────────────────────────────────
// Clock
// ─────────────────────────────────────────────────────────────────────────────
logic clk = 0;
always #10 clk = ~clk;   // 50 MHz, 20 ns period

// ─────────────────────────────────────────────────────────────────────────────
// DUT ports
// ─────────────────────────────────────────────────────────────────────────────
logic                  rst_n;
logic                  param_write_en;
logic [2:0]            param_addr;
logic [DATA_WIDTH-1:0] param_data;
logic [DATA_WIDTH-1:0] gamma_reg, c_reg;
logic [DATA_WIDTH-1:0] bias_reg [5];
logic [7:0]            num_sv_per_class [5];
logic                  qspi_valid;
logic [DATA_WIDTH-1:0] qspi_data;
logic                  qspi_ready;
logic [17:0]           sv_ram_addr;
logic [DATA_WIDTH-1:0] sv_ram_rdata;
logic                  sv_ram_ren;
logic [17:0]           work_ram_addr;
logic [DATA_WIDTH-1:0] work_ram_wdata;
logic [DATA_WIDTH-1:0] work_ram_rdata;
logic                  work_ram_wen;
logic                  work_ram_ren;
logic                  start;
logic [9:0]            num_samples;
logic                  done;
logic                  error;
logic [3:0]            error_code;
logic [DATA_WIDTH-1:0] kernel_out;
logic                  kernel_valid;
logic                  kernel_ready;

// ─────────────────────────────────────────────────────────────────────────────
// DUT instantiation
// ─────────────────────────────────────────────────────────────────────────────
svm_compute_core #(
    .DATA_WIDTH   (DATA_WIDTH),
    .FRAC_BITS    (10),
    .FEATURE_DIM  (FEATURE_DIM),
    .NUM_SV       (NUM_SV_INST),
    .DEFAULT_GAMMA(0.25),
    .DEFAULT_C    (1.0)
) dut (
    .clk              (clk),
    .rst_n            (rst_n),
    .param_write_en   (param_write_en),
    .param_addr       (param_addr),
    .param_data       (param_data),
    .gamma_reg        (gamma_reg),
    .c_reg            (c_reg),
    .bias_reg         (bias_reg),
    .num_sv_per_class (num_sv_per_class),
    .qspi_valid       (qspi_valid),
    .qspi_data        (qspi_data),
    .qspi_ready       (qspi_ready),
    .sv_ram_addr      (sv_ram_addr),
    .sv_ram_rdata     (sv_ram_rdata),
    .sv_ram_ren       (sv_ram_ren),
    .work_ram_addr    (work_ram_addr),
    .work_ram_wdata   (work_ram_wdata),
    .work_ram_rdata   (work_ram_rdata),
    .work_ram_wen     (work_ram_wen),
    .work_ram_ren     (work_ram_ren),
    .vbatt_warn      (1'b0),
    .vbatt_ok        (1'b1),
    .start            (start),
    .num_samples      (num_samples),
    .done             (done),
    .error            (error),
    .error_code       (error_code),
    .kernel_out       (kernel_out),
    .kernel_valid     (kernel_valid),
    .kernel_ready     (kernel_ready)
);

// ─────────────────────────────────────────────────────────────────────────────
// SV RAM model (read-only, 1-cycle registered latency)
// ─────────────────────────────────────────────────────────────────────────────
logic [DATA_WIDTH-1:0] sv_ram_model [0 : RAM_SIZE-1];

always_ff @(posedge clk)
    if (sv_ram_ren)
        sv_ram_rdata <= sv_ram_model[sv_ram_addr];

// ─────────────────────────────────────────────────────────────────────────────
// Workspace RAM — DUT writes kernel results here; testbench ignores reads
// ─────────────────────────────────────────────────────────────────────────────
assign work_ram_rdata = '0;

// ─────────────────────────────────────────────────────────────────────────────
// Test data arrays
// ─────────────────────────────────────────────────────────────────────────────
logic [DATA_WIDTH-1:0] test_features      [0 : N_TEST*FEATURE_DIM - 1];
logic [DATA_WIDTH-1:0] expected_kernels   [0 : N_TEST*NUM_SV_INST - 1];
logic [7:0]            test_labels        [0 : N_TEST-1];
logic [7:0]            expected_preds     [0 : N_TEST-1];

// Per-heartbeat kernel collection buffer
integer kernel_buf [0 : NUM_SV_INST-1];
integer kernel_count;

// ─────────────────────────────────────────────────────────────────────────────
// Log file handle
// ─────────────────────────────────────────────────────────────────────────────
integer log_fd;
bit     any_error;

// ─────────────────────────────────────────────────────────────────────────────
// Task: hard reset
// ─────────────────────────────────────────────────────────────────────────────
task automatic do_reset();
    rst_n          = 0;
    param_write_en = 0;
    param_addr     = '0;
    param_data     = '0;
    qspi_valid     = 0;
    qspi_data      = '0;
    start          = 0;
    num_samples    = 10'd1;
    kernel_ready   = 1'b1;
    for (int i = 0; i < 5; i++) num_sv_per_class[i] = 8'd0;
    repeat(4) @(posedge clk);
    rst_n = 1'b1;
    @(posedge clk);
endtask

// ─────────────────────────────────────────────────────────────────────────────
// Task: write gamma parameter register
// gamma = 0.25  →  Q6.10 = round(0.25 × 1024) = 256 = 16'h0100
// ─────────────────────────────────────────────────────────────────────────────
task automatic program_gamma(input logic [DATA_WIDTH-1:0] val);
    @(posedge clk);
    param_write_en = 1'b1;
    param_addr     = 3'b000;
    param_data     = val;
    @(posedge clk);
    param_write_en = 1'b0;
endtask

// ─────────────────────────────────────────────────────────────────────────────
// Task: stream FEATURE_DIM words through QSPI ready/valid
// ─────────────────────────────────────────────────────────────────────────────
task automatic feed_heartbeat(input integer hb_idx);
    integer fi;
    @(posedge clk);
    while (!qspi_ready) @(posedge clk);

    for (fi = 0; fi < FEATURE_DIM; fi++) begin
        qspi_valid = 1'b1;
        qspi_data  = test_features[hb_idx * FEATURE_DIM + fi];
        @(posedge clk);
        while (!qspi_ready && fi < FEATURE_DIM-1) @(posedge clk);
    end
    qspi_valid = 1'b0;
    qspi_data  = '0;
endtask

// ─────────────────────────────────────────────────────────────────────────────
// Task: collect N_SV kernel outputs from kernel_valid/kernel_ready stream
// ─────────────────────────────────────────────────────────────────────────────
task automatic collect_kernels(input integer n_sv);
    bit  done_seen;
    int  timeout;
    done_seen    = 0;
    kernel_count = 0;
    timeout      = 0;

    while (!done_seen && timeout < 500_000) begin
        @(posedge clk);
        if (kernel_valid) begin
            kernel_buf[kernel_count] = $signed(kernel_out);
            kernel_count++;
        end
        if (done) done_seen = 1'b1;
        timeout++;
    end

    if (kernel_count !== n_sv) begin
        $fdisplay(log_fd,
            "  [WARNING] collected %0d kernels, expected %0d  (t=%0t)",
            kernel_count, n_sv, $time);
        $display("WARNING: kernel count mismatch: got %0d expected %0d",
                 kernel_count, n_sv);
    end
    @(posedge clk);
endtask

// ─────────────────────────────────────────────────────────────────────────────
// Function: OvO decision function → predicted class (0..4)
// ─────────────────────────────────────────────────────────────────────────────
function automatic integer ovo_classify();
    real    kern_r   [NUM_SV_INST];
    real    dec      [N_PAIRS];
    integer votes    [5];
    integer pair_idx, best_class, best_votes;
    integer k, a, b, s;
    real    dc_val;

    for (k = 0; k < N_SV_TOTAL; k++)
        kern_r[k] = $itor($signed(16'(kernel_buf[k]))) / SCALE_R;

    pair_idx = 0;
    for (a = 0; a < 5; a++) begin
        for (b = a+1; b < 5; b++) begin
            dec[pair_idx] = INTERCEPT[pair_idx];

            for (s = SV_START[a]; s < SV_START[a] + SV_COUNTS[a]; s++) begin
                case (b - 1)
                    0: dc_val = DUAL_COEF_0[s];
                    1: dc_val = DUAL_COEF_1[s];
                    2: dc_val = DUAL_COEF_2[s];
                    3: dc_val = DUAL_COEF_3[s];
                    default: dc_val = 0.0;
                endcase
                dec[pair_idx] = dec[pair_idx] + dc_val * kern_r[s];
            end

            for (s = SV_START[b]; s < SV_START[b] + SV_COUNTS[b]; s++) begin
                case (a)
                    0: dc_val = DUAL_COEF_0[s];
                    1: dc_val = DUAL_COEF_1[s];
                    2: dc_val = DUAL_COEF_2[s];
                    3: dc_val = DUAL_COEF_3[s];
                    default: dc_val = 0.0;
                endcase
                dec[pair_idx] = dec[pair_idx] + dc_val * kern_r[s];
            end

            pair_idx++;
        end
    end

    for (a = 0; a < 5; a++) votes[a] = 0;
    pair_idx = 0;
    for (a = 0; a < 5; a++) begin
        for (b = a+1; b < 5; b++) begin
            if (dec[pair_idx] > 0.0) votes[a]++;
            else                     votes[b]++;
            pair_idx++;
        end
    end

    best_class = 0; best_votes = votes[0];
    for (a = 1; a < 5; a++) begin
        if (votes[a] > best_votes) begin
            best_votes = votes[a];
            best_class = a;
        end
    end
    return best_class;
endfunction

// ─────────────────────────────────────────────────────────────────────────────
// Task: log one heartbeat result
// ─────────────────────────────────────────────────────────────────────────────
task automatic log_heartbeat(
    input integer hb_idx,
    input integer true_lbl,
    input integer pred_lbl,
    input real    kernel_mae,
    input integer n_ok_k
);
    integer k;
    real    k_r;

    $fdisplay(log_fd, "");
    $fdisplay(log_fd, "------------------------------------------------------------");
    $fdisplay(log_fd, "[Heartbeat %0d / %0d]  t = %0t", hb_idx+1, N_TEST, $time);
    $fdisplay(log_fd, "  True class  : %s (%0d)", CLASS_NAME[true_lbl], true_lbl);
    $fdisplay(log_fd, "  Predicted   : %s (%0d)  →  %s",
        CLASS_NAME[pred_lbl], pred_lbl,
        (pred_lbl == true_lbl) ? "CORRECT" : "WRONG");
    $fdisplay(log_fd, "  Kernels collected : %0d / %0d", kernel_count, N_SV_TOTAL);
    $fdisplay(log_fd, "  Kernel MAE  (hw vs pre-computed, Q6.10): %.6f", kernel_mae);
    $fdisplay(log_fd, "  Kernel match within +/-%0d LSB : %0d / %0d  (%.1f%%)",
        KERNEL_TOL, n_ok_k, N_SV_TOTAL,
        100.0 * $itor(n_ok_k) / $itor(N_SV_TOTAL));
    $fdisplay(log_fd, "  DUT error flag : %s", error ? "SET !" : "clear");

    $fwrite(log_fd, "  Kernels [0..9] :");
    for (k = 0; k < 10 && k < N_SV_TOTAL; k++) begin
        k_r = $itor($signed(16'(kernel_buf[k]))) / SCALE_R;
        $fwrite(log_fd, " %.4f", k_r);
    end
    $fdisplay(log_fd, "");
endtask

// ─────────────────────────────────────────────────────────────────────────────
// Main stimulus
// ─────────────────────────────────────────────────────────────────────────────
integer hb, k, sv, fi;
integer correct_count;
integer pred_class;
integer true_lbl, exp_lbl;
integer n_ok_kernel;
integer abs_diff;
real    diff_sum, kernel_mae;
real    total_mae;

initial begin
    log_fd = $fopen("svm_classifier.log", "w");
    if (!log_fd) begin $display("ERROR: cannot open svm_classifier.log"); $finish; end

    $readmemh("sv_ram.hex",           sv_ram_model);
    $readmemh("test_features.hex",    test_features);
    $readmemh("expected_kernels.hex", expected_kernels);
    $readmemh("test_labels.hex",      test_labels);
    $readmemh("expected_preds.hex",   expected_preds);

    $fdisplay(log_fd, "================================================================");
    $fdisplay(log_fd, "  SVM Compute Core — Classification Testbench (LUT kernel)");
    $fdisplay(log_fd, "  ECE 410 · 5-Class Cardiac Arrhythmia Detection · MIT-BIH");
    $fdisplay(log_fd, "================================================================");
    $fdisplay(log_fd, "  Clock      : 50 MHz  (20 ns period)");
    $fdisplay(log_fd, "  Format     : Q6.10 fixed-point  (scale = 1024)");
    $fdisplay(log_fd, "  gamma      : 0.25  (Q6.10 = 0x0100 = 256)");
    $fdisplay(log_fd, "  Kernel     : range-reduction LUT  exp(-I) x exp(-F)");
    $fdisplay(log_fd, "  Features   : 256-dim multi-scale (128 beat + 64 mean + 64 RR)");
    $fdisplay(log_fd, "  NUM_SV     : %0d (DUT parameter)   N_SV_active: %0d",
              NUM_SV_INST, N_SV_TOTAL);
    $fdisplay(log_fd, "  SVs/class  : Normal=%0d  PVC=%0d  AFib=%0d  VT=%0d  SVT=%0d",
              SV_COUNTS[0], SV_COUNTS[1], SV_COUNTS[2], SV_COUNTS[3], SV_COUNTS[4]);
    $fdisplay(log_fd, "  Test beats : %0d (one per class)", N_TEST);
    $fdisplay(log_fd, "  Pass thresh: %0d / %0d correct (>= %0.0f%%)",
              PASS_THRESH, N_TEST, 100.0*PASS_THRESH/N_TEST);
    $fdisplay(log_fd, "");

    correct_count = 0;
    total_mae     = 0.0;
    any_error     = 0;

    for (hb = 0; hb < N_TEST; hb++) begin

        $display("[%0t] Heartbeat %0d / %0d  (%s)",
                 $time, hb+1, N_TEST, CLASS_NAME[test_labels[hb]]);

        if (hb == 0) begin
            $dumpfile("svm_waveform_hb0.vcd");
            $dumpvars(2, dut);
        end

        // ── reset ─────────────────────────────────────────────────────────────
        do_reset();

        // ── program gamma = 0.25 → Q6.10 = 256 = 0x0100 ────────────────────
        program_gamma(16'h0100);

        // ── set SV counts per class ──────────────────────────────────────────
        for (sv = 0; sv < 5; sv++)
            num_sv_per_class[sv] = SV_COUNTS[sv];

        // ── start single-heartbeat batch ─────────────────────────────────────
        num_samples = 10'd1;
        @(posedge clk);
        start = 1'b1;
        @(posedge clk);
        start = 1'b0;

        // ── stream 256 features via QSPI ─────────────────────────────────────
        feed_heartbeat(hb);

        // ── collect N_SV_TOTAL kernel outputs ────────────────────────────────
        collect_kernels(N_SV_TOTAL);

        if (error && error_code < 4'h8) any_error = 1; // codes >= 0x8 are advisory (expected)
        if (hb == 0) $dumpoff;

        // ── kernel MAE vs pre-computed ───────────────────────────────────────
        diff_sum    = 0.0;
        n_ok_kernel = 0;
        for (k = 0; k < N_SV_TOTAL; k++) begin
            abs_diff = kernel_buf[k] - $signed({1'b0, expected_kernels[hb*NUM_SV_INST+k]});
            if (abs_diff < 0) abs_diff = -abs_diff;
            diff_sum += $itor(abs_diff);
            if (abs_diff <= KERNEL_TOL) n_ok_kernel++;
        end
        kernel_mae  = diff_sum / ($itor(N_SV_TOTAL) * SCALE_R);
        total_mae  += kernel_mae;

        // ── OvO classification ───────────────────────────────────────────────
        pred_class = ovo_classify();
        true_lbl   = test_labels[hb];
        exp_lbl    = expected_preds[hb];
        if (pred_class === true_lbl) correct_count++;

        log_heartbeat(hb, true_lbl, pred_class, kernel_mae, n_ok_kernel);

        $display("        → predicted %-7s  %s  (kernel_mae=%.5f)",
                 CLASS_NAME[pred_class],
                 (pred_class === true_lbl) ? "CORRECT" : "WRONG",
                 kernel_mae);

    end  // for hb

    // ── Final summary ─────────────────────────────────────────────────────────
    $fdisplay(log_fd, "");
    $fdisplay(log_fd, "================================================================");
    $fdisplay(log_fd, "RESULTS SUMMARY");
    $fdisplay(log_fd, "================================================================");
    $fdisplay(log_fd, "  Heartbeat results:");
    for (hb = 0; hb < N_TEST; hb++)
        $fdisplay(log_fd, "    HB %0d  True: %-7s  Expected: %-7s  %s",
            hb, CLASS_NAME[test_labels[hb]],
            CLASS_NAME[expected_preds[hb]],
            (test_labels[hb] == expected_preds[hb]) ? "matched" : "differs");
    $fdisplay(log_fd, "");
    $fdisplay(log_fd, "  Classification accuracy : %0d / %0d  (%.1f%%)",
        correct_count, N_TEST,
        100.0 * $itor(correct_count) / $itor(N_TEST));
    $fdisplay(log_fd, "  Mean kernel MAE         : %.6f  (Q6.10 float, tolerance +/-%0d LSB)",
        total_mae / $itor(N_TEST), KERNEL_TOL);
    $fdisplay(log_fd, "  DUT error flag          : %s",
        any_error ? "ASSERTED (real fault — failure)"
                  : "never asserted (ERR_WARMING_UP advisory expected, ignored)");
    $fdisplay(log_fd, "  Pass threshold          : >= %0d / %0d correct",
        PASS_THRESH, N_TEST);
    $fdisplay(log_fd, "");

    if ((correct_count >= PASS_THRESH) && !any_error) begin
        $fdisplay(log_fd, "================================================================");
        $fdisplay(log_fd, "BUILD GRADE:  PASS");
        $fdisplay(log_fd, "================================================================");
        $display("================================================================");
        $display("BUILD GRADE:  PASS  (%0d/%0d correct, error=%0b)",
                 correct_count, N_TEST, any_error);
        $display("================================================================");
    end else begin
        $fdisplay(log_fd, "================================================================");
        $fdisplay(log_fd, "BUILD GRADE:  FAIL");
        $fdisplay(log_fd, "  Reason: accuracy %0d/%0d < threshold %0d/%0d%s",
            correct_count, N_TEST, PASS_THRESH, N_TEST,
            any_error ? " | DUT error flag was set" : "");
        $fdisplay(log_fd, "================================================================");
        $display("================================================================");
        $display("BUILD GRADE:  FAIL  (%0d/%0d correct, error=%0b)",
                 correct_count, N_TEST, any_error);
        $display("================================================================");
    end

    $fdisplay(log_fd, "");
    $fdisplay(log_fd, "Waveform : svm_waveform_hb0.vcd  (heartbeat 0, depth 2)");
    $fdisplay(log_fd, "Sim end  : t = %0t", $time);

    $fclose(log_fd);
    $display("Log written  → svm_classifier.log");
    $display("Waveform     → svm_waveform_hb0.vcd  (heartbeat 0)");
    $finish;
end

// ─────────────────────────────────────────────────────────────────────────────
// Watchdog
// ─────────────────────────────────────────────────────────────────────────────
initial begin
    #200_000_000;
    $fdisplay(log_fd, "[WATCHDOG] Simulation timeout at t=%0t!", $time);
    $fdisplay(log_fd, "BUILD GRADE:  FAIL  (timeout)");
    $fclose(log_fd);
    $display("BUILD GRADE:  FAIL  (watchdog timeout)");
    $finish;
end

endmodule
