// Auto-generated by OpenLane
module crossbar(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[7:0] v0,
  input[7:0] v1,
  input[7:0] v2,
  input[7:0] v3,
  output[9:0] i0,
  output[9:0] i1,
  output[9:0] i2,
  output[9:0] i3
);
endmodule
